### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by daijiu9** [Suhyun777/CVPR23-GAP#2]
I would like to ask a question. There are no data.hdf5 and labels.json files in the miniImagenet and omniglot data sets.

**Comment by Suhyun777** [comment]
Hi, thank you for your interest in my work!

I have noticed an issue with the dataset code file in torchmeta. It's essential to use our dataset code file instead of the one provided by torchmeta. Additionally, to generate the data.hdf5 and labels.json files, you need to include the --download argument when running the command for the first time. It seems like you might have run the command without this argument initially. If you encounter any further issues, please post an additional issue at anytime. Thank you!

**Comment by Suhyun777** [comment]
> I would like to ask a question. There are no data.hdf5 and labels.json files in the miniImagenet and omniglot data sets.

Hi, thank you for your interest in my work!

I have noticed an issue with the dataset code file in torchmeta. It's essential to use our dataset code file instead of the one provided by torchmeta. Additionally, to generate the data.hdf5 and labels.json files, you need to include the --download argument when running the command for the first time. It seems like you might have run the command without this argument initially. If you encounter any further issues, please post an additional issue at anytime. Thank you!
